INCLUDE IRVINE32.INC
.DATA
	msg byte "We are Learning Assembly Language",10,13,0
	msg1 byte "HELLO WORLD",0
.CODE
MAIN PROC
	;COMMENTS
	CALL CLRSCR
	LEA EDX, MSG
	CALL WRITESTRING
	MOV EDX, OFFSET MSG1
	CALL WRITESTRING
	CALL CRLF
	EXIT
MAIN ENDP
END MAIN
